ghost:
  image: gold/ghost
  ports:
    - ${public_port}:2368
  command: npm start --production
  restart: always
  volumes:
    - ${ghost_content}:/var/lib/ghost
  environment:
    GHOST_URL: ${ghost_url}
    PROD_FORCE_ADMIN_SSL: ${ghost_admin_ssl}
    MAIL_FROM: ${mail_from}
    MAIL_HOST: ${mail_host}
    MAIL_SSL: ${mail_ssl}
    MAIL_PORT: ${mail_port}
    MAIL_USERNAME: ${mail_username}
    MAIL_PASSWORD: ${mail_password}
