.catalog:
  name: "Wordpress"
  version: "v0.2-psander"
  description: "Blog tool, publishing platform and CMS"
  uuid: Wordpress-0
  minimum_rancher_version: v0.51.0
  questions:    
    - variable: public_port
      description: "public port to access the wordpress site"
      label: "Public Port"
      required: true
      default: "80"
      type: "int"
    - variable: mysql_user_password
      description: "user password for database"
      label: "DB User Password"
      required: true
      type: string
    - variable: mysql_root_password
      description: "root password for database"
      label: "DB Root Password"
      required: true
      type: string      
    - variable: backup_path
      description: "local path to backups"
      label: "Backup Path"
      required: true
      type: string
    - variable: backup_time
      description: "Crontab syntax (Default: 1 am, on the 0 and 4 day (Sunday and Thursday))"
      label: "Time"
      required: true
      default: "0 1 * * 0,4"
      type: string
      
wordpress:
